const rawData = [
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "배당금수익",
    amount: 23645920,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "유형자산처분이익",
    amount: 76692200,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "이자수익",
    amount: 80873400,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "자산수증이익",
    amount: 14741820,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "잡이익",
    amount: 35937980,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "개서료",
    amount: 5438780,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프용품판매",
    amount: 44089750,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프장이용료",
    amount: 635834150,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "공사수입",
    amount: 47498530,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "기타수입",
    amount: 19942320,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "대여료",
    amount: 112741880,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "식음료",
    amount: 149192250,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "연습장수입",
    amount: 69557560,
  },
  {
    transactionDate: "2024-09",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "임대매출",
    amount: 34290620,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기부금",
    amount: 8176590,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기타의대손상각비",
    amount: 23544050,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "유형자산처분손실",
    amount: 11805430,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "잡손실",
    amount: 12969860,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "감가상각비",
    amount: 106387450,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "공사원가",
    amount: 28322710,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "광고선전비",
    amount: 1446200,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "대여원가",
    amount: 4120920,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "무형자산상각비",
    amount: 3668160,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "보험료",
    amount: 5731650,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "상품매출원가",
    amount: 9319800,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세금과공과",
    amount: 195460430,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "소모품비",
    amount: 39119690,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "수선비",
    amount: 14891020,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "식음료매출원가",
    amount: 47812320,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "여비교통비",
    amount: 9450220,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "연습장원가",
    amount: 10825510,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "전력비",
    amount: 9451360,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급수수료",
    amount: 144567980,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급임차료",
    amount: 27383340,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "차량유지비",
    amount: 7553790,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "코스관리비",
    amount: 199627880,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "통신비",
    amount: 3684600,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "협회비",
    amount: 1409810,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "호텔이용원가",
    amount: 1788390,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "급여",
    amount: 187440930,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "복리후생비",
    amount: 40779250,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "잡급",
    amount: 4888550,
  },
  {
    transactionDate: "2024-09",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "퇴직급여",
    amount: 19820590,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "배당금수익",
    amount: 4773570,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "유형자산처분이익",
    amount: 142471960,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "이자수익",
    amount: 119225620,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "자산수증이익",
    amount: 30313790,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "잡이익",
    amount: 44269110,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프용품판매",
    amount: 31783680,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프장이용료",
    amount: 789457330,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "공사수입",
    amount: 31442270,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "기타수입",
    amount: 38879380,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "대여료",
    amount: 120941140,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "식음료",
    amount: 176629330,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "연습장수입",
    amount: 30362970,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "임대매출",
    amount: 42812040,
  },
  {
    transactionDate: "2024-08",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "호텔이용수입",
    amount: 15355980,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기부금",
    amount: 5874240,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기타의대손상각비",
    amount: 40508290,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "매도가능증권처분손실",
    amount: 1409020,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "유형자산처분손실",
    amount: 26898690,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "잡손실",
    amount: 22824020,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "감가상각비",
    amount: 90252020,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "공사원가",
    amount: 7364730,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "광고선전비",
    amount: 1161280,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "무형자산상각비",
    amount: 4366720,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "보험료",
    amount: 3604030,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "상품매출원가",
    amount: 9609360,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세금과공과",
    amount: 191341560,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "소모품비",
    amount: 22296460,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "수선비",
    amount: 14013340,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "스포츠시설이용원가",
    amount: 1739670,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "식음료매출원가",
    amount: 49408080,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "여비교통비",
    amount: 5775560,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "연습장원가",
    amount: 6346840,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "전력비",
    amount: 12032650,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급수수료",
    amount: 165422800,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급임차료",
    amount: 35259410,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "차량유지비",
    amount: 11323180,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "코스관리비",
    amount: 183196980,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "판매촉진비",
    amount: 3046010,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "급여",
    amount: 199690970,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "복리후생비",
    amount: 33625410,
  },
  {
    transactionDate: "2024-08",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "퇴직급여",
    amount: 28461140,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "배당금수익",
    amount: 5452150,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "유형자산처분이익",
    amount: 83630730,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "이자수익",
    amount: 116427470,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "자산수증이익",
    amount: 21439510,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "잡이익",
    amount: 64124760,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프용품판매",
    amount: 37040350,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프장이용료",
    amount: 633766620,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "공사수입",
    amount: 20792710,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "기타수입",
    amount: 30742280,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "대여료",
    amount: 197975710,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "식음료",
    amount: 157965760,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "연습장수입",
    amount: 2774390,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "임대매출",
    amount: 21854470,
  },
  {
    transactionDate: "2024-07",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "호텔이용수입",
    amount: 3136950,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기부금",
    amount: 3256300,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기타의대손상각비",
    amount: 28255210,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "유형자산처분손실",
    amount: 11567950,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "잡손실",
    amount: 8259360,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "감가상각비",
    amount: 99320120,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "공사원가",
    amount: 11134160,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "광고선전비",
    amount: 12359270,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "대여원가",
    amount: 3057370,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "리스료",
    amount: 2075990,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "무형자산상각비",
    amount: 11276790,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "보험료",
    amount: 18382960,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "상품매출원가",
    amount: 20431530,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세금과공과",
    amount: 173187320,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "소모품비",
    amount: 18358270,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "수선비",
    amount: 9678890,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "식음료매출원가",
    amount: 61126790,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "여비교통비",
    amount: 4463540,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "연습장원가",
    amount: 9725710,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "전력비",
    amount: 4030120,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급수수료",
    amount: 150965380,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급임차료",
    amount: 28743800,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "차량유지비",
    amount: 7476440,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "코스관리비",
    amount: 227813390,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "통신비",
    amount: 3097620,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "급여",
    amount: 163252430,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "복리후생비",
    amount: 60755430,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "잡급",
    amount: 4117250,
  },
  {
    transactionDate: "2024-07",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "퇴직급여",
    amount: 7962920,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "배당금수익",
    amount: 23524730,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "유형자산처분이익",
    amount: 99756390,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "이자수익",
    amount: 111487950,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "자산수증이익",
    amount: 18512940,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "잡이익",
    amount: 48490490,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프용품판매",
    amount: 41616530,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프장이용료",
    amount: 703532370,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "공사수입",
    amount: 27852060,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "기타수입",
    amount: 42693730,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "대여료",
    amount: 130333670,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "세탁수입",
    amount: 9574250,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "식음료",
    amount: 179191190,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "연습장수입",
    amount: 2042110,
  },
  {
    transactionDate: "2024-06",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "임대매출",
    amount: 21729540,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기부금",
    amount: 9586130,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기타의대손상각비",
    amount: 26828760,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "매도가능증권처분손실",
    amount: 500500,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "보상비",
    amount: 2147900,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "유형자산처분손실",
    amount: 25477390,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "잡손실",
    amount: 19109800,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "감가상각비",
    amount: 94945390,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "공사원가",
    amount: 25204180,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "광고선전비",
    amount: 588380,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "대여원가",
    amount: 4727520,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "도서인쇄비",
    amount: 1629000,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "무형자산상각비",
    amount: 3172350,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "보험료",
    amount: 17306420,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "상품매출원가",
    amount: 30414840,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세금과공과",
    amount: 179141780,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "소모품비",
    amount: 9944680,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "수선비",
    amount: 18723820,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "식음료매출원가",
    amount: 58709020,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "연습장원가",
    amount: 10010710,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "전력비",
    amount: 15890690,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급수수료",
    amount: 133320530,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급임차료",
    amount: 38492200,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "차량유지비",
    amount: 6880730,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "코스관리비",
    amount: 243266130,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "통신비",
    amount: 4459850,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "판매촉진비",
    amount: 1738640,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "호텔이용원가",
    amount: 2203450,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "급여",
    amount: 180574910,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "복리후생비",
    amount: 30216740,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "잡급",
    amount: 2212650,
  },
  {
    transactionDate: "2024-06",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "퇴직급여",
    amount: 18369390,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "배당금수익",
    amount: 30709940,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "유형자산처분이익",
    amount: 69089250,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "이자수익",
    amount: 110422050,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "임대료",
    amount: 1640940,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "자산수증이익",
    amount: 17767470,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "잡이익",
    amount: 39968280,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프용품판매",
    amount: 24896560,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프장이용료",
    amount: 749572190,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "공사수입",
    amount: 61225370,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "기타수입",
    amount: 58802920,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "대여료",
    amount: 113804990,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "식음료",
    amount: 170842180,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "연습장수입",
    amount: 33007660,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "임대매출",
    amount: 7239050,
  },
  {
    transactionDate: "2024-05",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "호텔이용수입",
    amount: 5008820,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기부금",
    amount: 5257620,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기타의대손상각비",
    amount: 27712520,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "매도가능증권처분손실",
    amount: 4394080,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "보상비",
    amount: 3019840,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "유형자산처분손실",
    amount: 15469580,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "잡손실",
    amount: 31407250,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "감가상각비",
    amount: 80824240,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "공사원가",
    amount: 7755240,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "광고선전비",
    amount: 11899570,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "도서인쇄비",
    amount: 4419400,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "무형자산상각비",
    amount: 1814210,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "보험료",
    amount: 4292390,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "상품매출원가",
    amount: 14103170,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세금과공과",
    amount: 152704210,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "소모품비",
    amount: 13351050,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "수선비",
    amount: 9077640,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "식음료매출원가",
    amount: 46359750,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "여비교통비",
    amount: 9520310,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "연습장원가",
    amount: 196410,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "전력비",
    amount: 4970790,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급수수료",
    amount: 178793960,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급임차료",
    amount: 33498530,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "차량유지비",
    amount: 3399900,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "코스관리비",
    amount: 241741610,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "통신비",
    amount: 6152070,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "판매촉진비",
    amount: 4055140,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "급여",
    amount: 256822930,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "복리후생비",
    amount: 40584800,
  },
  {
    transactionDate: "2024-05",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "퇴직급여",
    amount: 29130510,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "배당금수익",
    amount: 10879130,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "수수료수입",
    amount: 2049030,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "유형자산처분이익",
    amount: 58570890,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "이자수익",
    amount: 85290760,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "자산수증이익",
    amount: 7786310,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "잡이익",
    amount: 80102330,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프용품판매",
    amount: 25568980,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프장이용료",
    amount: 845059200,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "공사수입",
    amount: 26338320,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "기타수입",
    amount: 49415360,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "대여료",
    amount: 163638780,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "세탁수입",
    amount: 3286370,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "식음료",
    amount: 182610560,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "연습장수입",
    amount: 31076710,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "임대매출",
    amount: 14956010,
  },
  {
    transactionDate: "2024-04",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "호텔이용수입",
    amount: 7973650,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기부금",
    amount: 7806930,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기타의대손상각비",
    amount: 29962770,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "매도가능증권처분손실",
    amount: 4077990,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "유형자산처분손실",
    amount: 34904000,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "잡손실",
    amount: 1405500,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "감가상각비",
    amount: 95537980,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "공사원가",
    amount: 17782470,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "광고선전비",
    amount: 7239240,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "교육훈련비",
    amount: 4004280,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "도서인쇄비",
    amount: 1464180,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "무형자산상각비",
    amount: 5600960,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "보험료",
    amount: 6605970,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "사무용품비",
    amount: 3602480,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "상품매출원가",
    amount: 8399890,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세금과공과",
    amount: 193875880,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "소모품비",
    amount: 24768570,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "수선비",
    amount: 15195840,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "식음료매출원가",
    amount: 54441150,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "여비교통비",
    amount: 930400,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "연습장원가",
    amount: 4120510,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "전력비",
    amount: 21093790,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급수수료",
    amount: 156286100,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급임차료",
    amount: 18111350,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "차량유지비",
    amount: 6700560,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "코스관리비",
    amount: 218466050,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "협회비",
    amount: 2915570,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "급여",
    amount: 180800000,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "복리후생비",
    amount: 37486520,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "잡급",
    amount: 1557670,
  },
  {
    transactionDate: "2024-04",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "퇴직급여",
    amount: 28061630,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "배당금수익",
    amount: 31608040,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "유형자산처분이익",
    amount: 80601960,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "이자수익",
    amount: 103162630,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "자산수증이익",
    amount: 22373840,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "잡이익",
    amount: 78438490,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프용품판매",
    amount: 23612870,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프장이용료",
    amount: 780638990,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "공사수입",
    amount: 29342360,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "기타수입",
    amount: 28285570,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "대여료",
    amount: 112677540,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "스포츠시설이용수입",
    amount: 4943550,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "식음료",
    amount: 79011580,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "연습장수입",
    amount: 19780360,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "임대매출",
    amount: 13803390,
  },
  {
    transactionDate: "2024-03",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "호텔이용수입",
    amount: 8162050,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기부금",
    amount: 5184850,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기타의대손상각비",
    amount: 23339690,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "매도가능증권처분손실",
    amount: 1094450,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "보상비",
    amount: 5733610,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "유형자산처분손실",
    amount: 32041480,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "잡손실",
    amount: 37268890,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "감가상각비",
    amount: 156243720,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "공사원가",
    amount: 7675400,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "광고선전비",
    amount: 3533390,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "교육훈련비",
    amount: 1148510,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "대여원가",
    amount: 1187050,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "도서인쇄비",
    amount: 2435820,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "무형자산상각비",
    amount: 5020230,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "보험료",
    amount: 18226950,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "상품매출원가",
    amount: 20218470,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세금과공과",
    amount: 154623200,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "소모품비",
    amount: 32568900,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "수선비",
    amount: 18879820,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "식음료매출원가",
    amount: 21163340,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "여비교통비",
    amount: 13015660,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "연습장원가",
    amount: 7325000,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "전력비",
    amount: 7951220,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급수수료",
    amount: 104995810,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급임차료",
    amount: 25439070,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "차량유지비",
    amount: 4301280,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "코스관리비",
    amount: 250524260,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "통신비",
    amount: 8080160,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "급여",
    amount: 220807290,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "복리후생비",
    amount: 38104990,
  },
  {
    transactionDate: "2024-03",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "퇴직급여",
    amount: 21389610,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "배당금수익",
    amount: 16680660,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "유형자산처분이익",
    amount: 37617770,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "이자수익",
    amount: 65079400,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "자산수증이익",
    amount: 14251890,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "잡이익",
    amount: 46692300,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프용품판매",
    amount: 27742460,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프장이용료",
    amount: 754100310,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "공사수입",
    amount: 24788260,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "기타수입",
    amount: 33482200,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "대여료",
    amount: 193423510,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "식음료",
    amount: 140638820,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "연습장수입",
    amount: 12658800,
  },
  {
    transactionDate: "2024-02",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "임대매출",
    amount: 939250,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기부금",
    amount: 6106720,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기타의대손상각비",
    amount: 30576540,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "보상비",
    amount: 9295290,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "유형자산처분손실",
    amount: 21738230,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "잡손실",
    amount: 32312070,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "감가상각비",
    amount: 114950720,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "공사원가",
    amount: 6521380,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "광고선전비",
    amount: 5714390,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "대여원가",
    amount: 8437540,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "도서인쇄비",
    amount: 3823710,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "무형자산상각비",
    amount: 5544160,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "보험료",
    amount: 14947160,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "상품매출원가",
    amount: 7027710,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세금과공과",
    amount: 150306460,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세탁원가",
    amount: 7665740,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "소모품비",
    amount: 35454800,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "수선비",
    amount: 17425740,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "식음료매출원가",
    amount: 45426440,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "여비교통비",
    amount: 2948440,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "연습장원가",
    amount: 7064730,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "전력비",
    amount: 22236040,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급수수료",
    amount: 147145290,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급임차료",
    amount: 29329980,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "차량유지비",
    amount: 8197810,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "코스관리비",
    amount: 201547850,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "통신비",
    amount: 3679080,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "판매촉진비",
    amount: 3533120,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "급여",
    amount: 185951160,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "복리후생비",
    amount: 36004090,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "잡급",
    amount: 2477570,
  },
  {
    transactionDate: "2024-02",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "퇴직급여",
    amount: 18745430,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "배당금수익",
    amount: 4697690,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "유형자산처분이익",
    amount: 107832380,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "이자수익",
    amount: 87110140,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "임대료",
    amount: 450960,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "자산수증이익",
    amount: 34168750,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "잡이익",
    amount: 19051830,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "개서료",
    amount: 7137730,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프용품판매",
    amount: 50905530,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프장이용료",
    amount: 812578190,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "공사수입",
    amount: 9797630,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "기타수입",
    amount: 32595060,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "대여료",
    amount: 150666590,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "식음료",
    amount: 108563230,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "연습장수입",
    amount: 41755100,
  },
  {
    transactionDate: "2024-01",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "임대매출",
    amount: 28270200,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기부금",
    amount: 14058870,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기타의대손상각비",
    amount: 33199010,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "보상비",
    amount: 2550570,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "유형자산처분손실",
    amount: 20696470,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "잡손실",
    amount: 24441890,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "감가상각비",
    amount: 84096250,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "공사원가",
    amount: 17976880,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "광고선전비",
    amount: 9490180,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "대여원가",
    amount: 6769140,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "무형자산상각비",
    amount: 2920430,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "보험료",
    amount: 10561330,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "상품매출원가",
    amount: 5270180,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세금과공과",
    amount: 172168690,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세탁원가",
    amount: 1460720,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "소모품비",
    amount: 44266990,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "수선비",
    amount: 8707250,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "식음료매출원가",
    amount: 48082250,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "여비교통비",
    amount: 309990,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "연습장원가",
    amount: 1084960,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "전력비",
    amount: 7937370,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급수수료",
    amount: 140338160,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급임차료",
    amount: 22932700,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "차량유지비",
    amount: 7074900,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "코스관리비",
    amount: 224398210,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "통신비",
    amount: 4017310,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "급여",
    amount: 177393270,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "복리후생비",
    amount: 24819370,
  },
  {
    transactionDate: "2024-01",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "퇴직급여",
    amount: 29634270,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "배당금수익",
    amount: 9990220,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "유형자산처분이익",
    amount: 96496790,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "이자수익",
    amount: 82158630,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "임대료",
    amount: 1714460,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "자산수증이익",
    amount: 4277700,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "잡이익",
    amount: 76362840,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프용품판매",
    amount: 41806490,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프장이용료",
    amount: 672177530,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "공사수입",
    amount: 7248440,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "기타수입",
    amount: 52973130,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "대여료",
    amount: 159118440,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "식음료",
    amount: 189702070,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "연습장수입",
    amount: 24688050,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "임대매출",
    amount: 19376330,
  },
  {
    transactionDate: "2023-12",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "호텔이용수입",
    amount: 1890820,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기부금",
    amount: 2651040,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기타의대손상각비",
    amount: 27441550,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "매도가능증권처분손실",
    amount: 1305070,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "보상비",
    amount: 2730100,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "유형자산처분손실",
    amount: 27551430,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "잡손실",
    amount: 27229750,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "감가상각비",
    amount: 89526600,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "공사원가",
    amount: 13004880,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "광고선전비",
    amount: 7448600,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "교육훈련비",
    amount: 5560030,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "대여원가",
    amount: 4798940,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "보험료",
    amount: 18904060,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "상품매출원가",
    amount: 8986180,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세금과공과",
    amount: 177833820,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "소모품비",
    amount: 37077750,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "수선비",
    amount: 25418130,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "스포츠시설이용원가",
    amount: 5602140,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "식음료매출원가",
    amount: 44440750,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "여비교통비",
    amount: 8869770,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "연습장원가",
    amount: 2460320,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "전력비",
    amount: 19502120,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급수수료",
    amount: 199553640,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급임차료",
    amount: 34036050,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "차량유지비",
    amount: 502680,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "코스관리비",
    amount: 210998800,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "통신비",
    amount: 3959280,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "판매촉진비",
    amount: 2547710,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "급여",
    amount: 136663070,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "복리후생비",
    amount: 52419460,
  },
  {
    transactionDate: "2023-12",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "퇴직급여",
    amount: 35556000,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "배당금수익",
    amount: 21973760,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "유형자산처분이익",
    amount: 84840720,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "이자수익",
    amount: 131350210,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "자산수증이익",
    amount: 24083140,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "잡이익",
    amount: 23330750,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프용품판매",
    amount: 29668370,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프장이용료",
    amount: 745654720,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "공사수입",
    amount: 37305980,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "기타수입",
    amount: 23344010,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "대여료",
    amount: 148599980,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "식음료",
    amount: 179423130,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "연습장수입",
    amount: 22265400,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "임대매출",
    amount: 33313560,
  },
  {
    transactionDate: "2023-11",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "호텔이용수입",
    amount: 8394230,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기부금",
    amount: 5293190,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기타의대손상각비",
    amount: 30408420,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "매도가능증권처분손실",
    amount: 3208680,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "보상비",
    amount: 3349410,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "유형자산처분손실",
    amount: 34694220,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "잡손실",
    amount: 43005380,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "감가상각비",
    amount: 82940300,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "공사원가",
    amount: 11637700,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "광고선전비",
    amount: 11352260,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "교육훈련비",
    amount: 764150,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "대여원가",
    amount: 7335270,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "도서인쇄비",
    amount: 4278150,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "무형자산상각비",
    amount: 6113880,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "보험료",
    amount: 4098290,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "상품매출원가",
    amount: 18504460,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세금과공과",
    amount: 152248380,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "소모품비",
    amount: 11439360,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "수선비",
    amount: 7646080,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "식음료매출원가",
    amount: 42654390,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "여비교통비",
    amount: 4873790,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "연습장원가",
    amount: 3447920,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "전력비",
    amount: 7391040,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급수수료",
    amount: 148208950,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급임차료",
    amount: 28049800,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "차량유지비",
    amount: 6822300,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "코스관리비",
    amount: 206172040,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "통신비",
    amount: 4367440,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "판매촉진비",
    amount: 4035640,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "호텔이용원가",
    amount: 2609590,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "급여",
    amount: 176556610,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "복리후생비",
    amount: 35496420,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "잡급",
    amount: 2740290,
  },
  {
    transactionDate: "2023-11",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "퇴직급여",
    amount: 28833210,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "배당금수익",
    amount: 10530190,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "유형자산처분이익",
    amount: 135520460,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "이자수익",
    amount: 131064610,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "자산수증이익",
    amount: 8376900,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "기타수익",
    description: "잡이익",
    amount: 84728740,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프용품판매",
    amount: 39606130,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "골프장이용료",
    amount: 911095250,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "공사수입",
    amount: 27795110,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "기타수입",
    amount: 36851480,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "대여료",
    amount: 194720340,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "식음료",
    amount: 135074890,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "연습장수입",
    amount: 6626100,
  },
  {
    transactionDate: "2023-10",
    transactionType: "수입",
    transactionCategory: "영업수익",
    description: "호텔이용수입",
    amount: 9738730,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기부금",
    amount: 7705140,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "기타의대손상각비",
    amount: 52368950,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "유형자산처분손실",
    amount: 34791870,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "영업외비용",
    description: "잡손실",
    amount: 30175370,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "감가상각비",
    amount: 123652610,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "공사원가",
    amount: 28694850,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "광고선전비",
    amount: 7394690,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "대여원가",
    amount: 2244060,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "무형자산상각비",
    amount: 3247780,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "보험료",
    amount: 9049000,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "상품매출원가",
    amount: 10103160,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세금과공과",
    amount: 160942960,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "세탁원가",
    amount: 3033910,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "소모품비",
    amount: 18747000,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "수선비",
    amount: 18099860,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "식음료매출원가",
    amount: 60470110,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "여비교통비",
    amount: 17438950,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "연습장원가",
    amount: 10633770,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "전력비",
    amount: 12719570,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급수수료",
    amount: 154465470,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "지급임차료",
    amount: 26361750,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "차량유지비",
    amount: 9343700,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "코스관리비",
    amount: 224279070,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "통신비",
    amount: 691680,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "운영비용",
    description: "협회비",
    amount: 1143730,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "급여",
    amount: 208965870,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "복리후생비",
    amount: 70008800,
  },
  {
    transactionDate: "2023-10",
    transactionType: "지출",
    transactionCategory: "인건비",
    description: "퇴직급여",
    amount: 18545190,
  },
];
